name: Laravel Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: school_sms
          MYSQL_USER: root
          MYSQL_PASSWORD: 
          MYSQL_ROOT_PASSWORD: 
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '8.0'

    - name: Install Dependencies
      run: composer install

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Database Migration
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: school_sms_testing
        DB_USERNAME: root
        DB_PASSWORD: 
      run: vendor/bin/phpunit
